export const FETCH_LOGIN_REQUEST = 'FETCH_LOGIN_REQUEST'
export const FETCH_LOGIN_SUCCESS = 'FETCH_LOGIN_SUCCESS'
export const FETCH_LOGIN_FAILURE = 'FETCH_HOME_FAILURE'
export const LOGOUT = 'USERS_LOGOUT'
export const FETCH_REGISTER_REQUEST = 'FETCH_LOGIN_REQUEST'
export const FETCH_REGISTER_SUCCESS = 'FETCH_LOGIN_SUCCESS'
export const FETCH_REGISTER_FAILURE = 'FETCH_HOME_FAILURE'



