export const productConstants = {
    PRODUCT_REQUEST: 'FETCH_PRODUCT_REQUEST',
    PRODUCT_SUCCESS: 'FETCH_PRODUCT_SUCCESS',
    PRODUCT_FAILURE: 'FETCH_PRODUCT_FAILURE',

    LOGIN_REQUEST: 'FETCH_LOGIN_REQUEST',
    LOGIN_SUCCESS: 'FETCH_LOGIN_SUCCESS',
    LOGIN_FAILURE: 'FETCH_LOGIN_FAILURE',
    
    LOGOUT: 'FETCH_LOGOUT',

    GETALL_REQUEST: 'FETCH_GETALL_REQUEST',
    GETALL_SUCCESS: 'FETCH_GETALL_SUCCESS',
    GETALL_FAILURE: 'FETCH_GETALL_FAILURE',

    DELETE_REQUEST: 'FETCH_DELETE_REQUEST',
    DELETE_SUCCESS: 'FETCH_DELETE_SUCCESS',
    DELETE_FAILURE: 'FETCH_DELETE_FAILURE'    
};
